### ISSUE TITLE
Add unit and/or integration tests

### ISSUE THREAD

**Issue by corneliusroemer** [domoritz/arrow-tools#11]
Some basic CI testing would be great to prevent regressions.

**Comment by domoritz** [comment]
Agreed. It probably doesn't make sense to test against exact binary matches but we could run the tools via the cli and check that the generated arrow or parquet parses correctly.

**Comment by corneliusroemer** [comment]
Yeah, arrow/parquet binaries don't need to be identical but we can round trip to a representation that should be invariant via a parquet/arrow -> csv converter, then check the csv is how it should be.

**Comment by domoritz** [comment]
Or we check in a test whether the arrow/parquet has the right values and types without going back to csv in the test.
