### ISSUE TITLE
Support `--delimiter '\t'`` in `csv2parquet`

### ISSUE THREAD

**Issue by ghuls** [domoritz/arrow-tools#117]
Support `--delimiter '\t'` in `csv2parquet`.

At the moment using it, gives:
```
error: invalid value '\t' for '--delimiter <DELIMITER>': too many characters in string  
```

A workaround is to encode a TAB in bash itself (`--delimiter $'\t'`), but supporting `--delimiter '\t'` directly would improve ergonomics.

**Comment by domoritz** [comment]
`--delimiter \t` seems to work in fish shell for me. Since arrow only accepts a character in the end rather than a string, I think it's reasonable to expect people to give the tab character, not a special string. Will close for now but if it comes up a lot, we can revisit.
