### ISSUE TITLE
Make binaries easily installable via: homebrew and/or conda-forge

### ISSUE THREAD

**Issue by corneliusroemer** [domoritz/arrow-tools#15]
To make the tools usable in general pipelines/instructions they need to be easily installed - can't require people to download binaries from Github or install rust/compile

**Comment by domoritz** [comment]
The biggest hurdles are that we need enough usage to justify having these tools in homebrew and setting up automatic updates. I think with currently 80 stars on GitHub we could argue that these packages are popular enough. So I think the next step is submitting a formula and setting up automatic updates. I won't have cycles for it but would be happy to accept a contribution.

**Comment by domoritz** [comment]
Looks like this could work: https://opensource.axo.dev/cargo-dist/book/installers/homebrew.html

**Comment by domoritz** [comment]
I added descriptions for how to download as well now.
