### ISSUE TITLE
Ability to compile to wasm/wasi

### ISSUE THREAD

**Issue by relcodedev** [domoritz/arrow-tools#16]
ability to compile the tools to wasm/wasi if possible.  It currently fails for E0554.

**Comment by domoritz** [comment]
Would you like to contribute this feature? I'm very open to prs.

**Comment by relcodedev** [comment]
Ok will do. not an expert in rust but I can give it a try.  It may not be possible if the issue is with one of the dependencies which I think is the case.  If the library uses any socket/network, it can't be compiled to wasi.  I can at least collect the information.
