### ISSUE TITLE
How to deal with the tsv file

### ISSUE THREAD

**Issue by dhtc** [domoritz/arrow-tools#17]
Thanks for the nice tools. Could you please give me some suggestion on how to deal with the tsv files?
I have run the code as below:
```shell
csv2parquet --header true -d '\t'  -p exprMatrix.tsv exprMatrix.parquet
```
the error messages are: 
error: invalid value '\t' for '--delimiter <DELIMITER>': too many characters in string
For more information, try '--help'.

So, how to use tab as the delimiter?

**Comment by jdiener** [comment]
assuming you are on some kind of Linux system, try this way:
csv2parquet --header true -d $'\t'  -p exprMatrix.tsv exprMatrix.parquet

Not the best explanation but gives a hint on what is happening:
https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html#ANSI_002dC-Quoting
