### ISSUE TITLE
Schema examples: Decimal128, Dictionary etc

### ISSUE THREAD

**Issue by taqtiqa-mark** [domoritz/arrow-tools#18]
Thanks for making these tools. They are great.

Would help non-Rustaceans to have schema examples for nontrivial types: Decimal128, Dictionary etc

**Comment by wynnw** [comment]
Are there examples in the apache-arrow project of this? I can't find any there. I have a use case where with pandas I can handle a integer array exported from postgresql and would love to be able to do something like `
OPTIONAL group my_intarray (LIST) {
  REPEATED group list {
    OPTIONAL INT64 element;
  }
}`

(this is a schema definition as reported by the pqrs and parquet-schema utilities from my existing parquet files.)

**Comment by wynnw** [comment]
I have found this: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#lists

and I'm trying to figure out how to express that in the schema json format.

**Comment by wynnw** [comment]
For anyone else who stumbles onto this - I ended up doing this PR for pqrs:
https://github.com/manojkarthick/pqrs/pull/51

which allowed me to see what the json schema should look like. At least I think it's what it should be according to api's I found.
