### ISSUE TITLE
json2parquet Parse json get error infer schema

### ISSUE THREAD

**Issue by relcodedev** [domoritz/arrow-tools#19]
I created small jsonl file called data.json. It has the three lines used from the README.md

data.json
```
{ "a": 42, "b": true }
{ "a": 12, "b": false }
{ "a": 7, "b": true }
```

```
json2parquest ./data.json ./data.parquet
```

Error: General("Error inferring schema: Json error: Not valid JSON: expected value at line 1 column 1")

Also can an example or point to docs to create the arrow json schema file?  Thanks.

**Comment by domoritz** [comment]
`json2parquet ../../data/simple.json simple.parquet` works fine for me. If you run `json2parquet ../../data/simple.json simple.parquet -n`, you will get the schema file.

```
> json2parquet ../../data/simple.json simple.parquet -n
Schema:
{
  "fields": [
    {
      "name": "a",
      "data_type": "Int64",
      "nullable": true,
      "dict_id": 0,
      "dict_is_ordered": false,
      "metadata": {}
    },
    {
      "name": "b",
      "data_type": "Boolean",
      "nullable": true,
      "dict_id": 0,
      "dict_is_ordered": false,
      "metadata": {}
    }
  ],
  "metadata": {}
}
```

**Comment by relcodedev** [comment]
The issue is in the file encoding.  The file I created was UTF8-BOM and the json2partquet seems to only supports UTF8.  I will update my original program to output UTF8 json. Thanks.

**Comment by domoritz** [comment]
Good catch and thanks for noting the solution here.

**Comment by relcodedev** [comment]
for others, this might help: 
on linux use the "file" command to see the encoding of the json files.
on windows, I use notepad++ to see the encoding.

**Comment by domoritz** [comment]
Could encoding be something that arrow or we need to fix?

**Comment by relcodedev** [comment]
I would suggest you support more encodings.  Other software supports UTF8-BOM encodings for json.  It looks like it is best practice that BOM is not needed but it depends on how the file was created.  In C#, default settings, files are written with BOM.  You have to explicitly exclude BOM.

**Comment by domoritz** [comment]
Would arrow need to fix this or us?

**Comment by relcodedev** [comment]
I think it should be json2parquet.  Whomever is opening the file should understand the encoding.

**Comment by domoritz** [comment]
Ok. I'd be open to a pull request.
