### ISSUE TITLE
json2parquet hangs and gets killed when writing large files

### ISSUE THREAD

**Issue by felix-hh** [domoritz/arrow-tools#59]
Hi there! First of all thank you for the tooling, it's incredibly powerful. I have been using `json2parquet` to process some intricate `.jsonl` files. I have had a good time with small sizes but not for the larger files. In my EC2 instance with 16GB of RAM, sometimes json2parquet will stall and never finish writing a parquet file, or the process gets killed. 

**Steps to reproduce**
I created a very simplified example that should be easy to reproduce with a schema, a file that works, and a file that doesn't. Unfortunately it only happens with large files. 

```
curl -OJ https://felixh-shareables.s3.us-west-2.amazonaws.com/schema.schema
curl -OJ https://felixh-shareables.s3.us-west-2.amazonaws.com/json2parquet-small.jsonl.gz # 80 MB compressed. 2GB uncompressed
curl -OJ https://felixh-shareables.s3.us-west-2.amazonaws.com/json2parquet-large.jsonl.gz # 1.1 GB compressed, 37 GB uncompressed

gunzip -c json2parquet-small.jsonl.gz | json2parquet -s schema.schema /dev/stdin json2parquet-small.parquet
# success - I can read the output to duckdb and confirm it works. 

gunzip -c json2parquet-large.jsonl.gz | json2parquet -s schema.schema /dev/stdin json2parquet-large.parquet
# Error. Killed
gunzip -c json2parquet-large.jsonl.gz | json2parquet -s schema.schema /dev/stdin /dev/stdout >| myout.parquet
# Hangs, see results from htop

# breaking up the steps
gunzip json2parquet-large.jsonl.gz
json2parquet json2parquet-large.jsonl json2parquet-large.parquet
# here, it hangs for a while. It creates a parquet file of 0 bytes. 
# After a long time, htop looks like in the image below. And then at some point the process gets killed.
```

**Results from htop**
<img width="988" alt="image" src="https://github.com/domoritz/arrow-tools/assets/50616313/18b40063-2487-4889-8b74-cd91c4633931">

I have let these processes hang for an hour. 

This happens regardless of whether I specify if I want a compressed output or not. 

Is there anything that I am missing in how I am using the tooling? The only think I can think about is `--data-page-size-limit`, `--write-batch-size` and `--max-row-group-size`. Please if you have time, let me know what could be going wrong. Thanks!

**Update:**
```
json2parquet json2parquet-large.jsonl json2parquet-large.parquet -s schema.schema --data-page-size-limit 1024 --write-batch-size 1024 --max-row-group-size 1024 -c gzip
```
The command above works, however, piping from the compressed file still fails
```
gunzip -c 1gb.jsonl.gz | json2parquet -s schema.schema -c gzip --data-page-size-limit 1024 --write-batch-size 1024 --max-row-group-size 1024 /dev/stdin myfile.parquet.gz
```
I would prefer not to unpack the files in memory as they can be very large, this one is already 37GB. 

**Update II:** 
OK I think I figured it out... 
```
gunzip -c 1gb.jsonl.gz | json2parquet -s schema.schema -c gzip --data-page-size-limit 1024 --write-batch-size 1024 --max-row-group-size 1024 --max-read-records 1  /dev/stdin myfile.parquet.gz
```

Here, **--max-read-records 1** seems to do the trick. It seems that although I am passing a schema it is still trying to infer the schema? Hence it has to wait for the entire unzipped stream to go into memory which will not happen since the uncompressed file of 37 GB >> 16 GB of memory.

**Comment by domoritz** [comment]
Hmm, that sounds like a bug. We should not try to infer the schema when it's provided.

**Comment by felix-hh** [comment]
Yes, I agree

**Comment by felix-hh** [comment]
Hey @domoritz what are the top enhancements you think are missing in the tooling right now? I'm not very familiar with rust but I might pick it up over the next couple of months and this might be a good project to work on.

**Comment by domoritz** [comment]
Awesome. I think the main things are in the GitHub issues.

Better support for stdin amd stdout and tests are the main things. Installing via homebrew would require some CI work and would also be useful.

**Comment by domoritz** [comment]
Can you try again to see whether these issues are still there?

**Comment by domoritz** [comment]
I'll close this for now since we have https://github.com/domoritz/arrow-tools/issues/14 which I think covers what's left here.
